### ISSUE TITLE
hello Robin, I have a problem in the site https://roadtoreact.com/

### ISSUE THREAD

**Issue by SquirrelJimmy** [rwieruch/parcel-react#2]
When I double click this site page, it appears a problem likes below: 
![5e677027-0ca3-450f-8fef-d99063ea4698](https://user-images.githubusercontent.com/24666536/36085173-afdf5c80-0ffe-11e8-8f5a-5e06aefbede9.png)
![1a7c5b5c-5a08-481a-8e89-a6c228bd552a](https://user-images.githubusercontent.com/24666536/36085251-68c325a6-0fff-11e8-8c4e-ff98e9316d1a.png)

if it's fixed,I think it's more beautiful
I can't find you from China, because I have no FB no TW 😆, sorry I open a Issues here

**Comment by rwieruch** [comment]
Got ya :) Thanks for reporting this. Why does it float in the middle of the screen with `bottom: 0` and `position: absolute`? Are you using Chrome? If so, which version is it? Position fixed would work, but then the footer would always be in the window. I would want to have it sticky at the bottom. Thanks again for writing!

**Comment by SquirrelJimmy** [comment]
My Chrome Version is 64.0.3282.140（official version） （64 bit）,oh, I find it just now, it's my problem, this is the picture
![problem](https://user-images.githubusercontent.com/24666536/36129119-8bbfd8c8-10a0-11e8-9d3f-9c4a4f6f7d6f.png)
 Sorry to have troubled you!

**Comment by rwieruch** [comment]
No worries :)
