### ISSUE TITLE
Deprication warning

### ISSUE THREAD

**Issue by zfadhli** [rwieruch/parcel-react#5]
I tried running this boilerplate. In the console there's a deprication warning

`Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class`

How do I fix this?

**Comment by rwieruch** [comment]
Hello @zulfadhli4141 The boilerplate got created almost a year ago. I guess it's not using the latest Parcel version. Can you try to update the libraries? And if this works out for you, you could create a Pull Request for this project 👍 Thank you for mentioning this!

**Comment by zfadhli** [comment]
It turns out that warning is actually from one of my chrome extension, not parcel.
